export const MokeProductData = [
    {
        id: 1,
        title: 'Roadster',
        subtitle: 'Solid Polo Collar T-shirt',
        description: 'The Lifestyle Co Men Navy Blue Solid Polo Collar T-shirt',
        category: 'Tshirts',
        rating: 4.1,
        ratingCount: '1.7k',
        price: '519',
        stock: 215,
        image: [
            '/images/black-t-shirt-1.jpg',
            '/images/black-t-shirt-2.jpg',
            '/images/black-t-shirt-3.jpg',
            '/images/black-t-shirt-4.jpg',
        ]
    },
    {
        id: 2,
        title: 'BULLMER',
        subtitle: 'Printed Oversized Cotton T-shirt',
        description: 'Tribal Printed Oversized Cotton T-shirt',
        category: 'Tshirts',
        rating: 3.6,
        ratingCount: '1.3k',
        price: '389',
        stock: 154,
        image: [
            '/images/cream-t-shirt-1.jpg',
            '/images/cream-t-shirt-2.jpg',
            '/images/cream-t-shirt-3.jpg',
            '/images/cream-t-shirt-4.jpg',
            '/images/cream-t-shirt-5.jpg',
        ]
    },
    {
        id: 3,
        title: 'Stormborn',
        subtitle: 'Pure Cotton Oversized T-shirt',
        description: 'Graphic Printed Drop Shoulder Sleeves Pure Cotton Oversized T-shirt',
        category: 'Tshirts',
        rating: 4.1,
        ratingCount: '2.4k',
        price: '539',
        stock: 154,
        image: [
            '/images/orange-t-shirt-1.jpg',
            '/images/orange-t-shirt-3.jpg',
            '/images/orange-t-shirt-4.jpg',
            '/images/orange-t-shirt-5.jpg',
        ]
    },
    {
        id: 4,
        title: 'Puma',
        subtitle: 'Men Colourblocked IDP Sneakers',
        description: 'Men White & Black Colourblocked IDP Sneakers',
        category: 'Shoes',
        rating: 4.2,
        ratingCount: '26.7k',
        price: '2474',
        stock: 75,
        image: [
            '/images/men-white-black-shoes-1.jpg',
            '/images/men-white-black-shoes-2.jpg',
            '/images/men-white-black-shoes-3.jpg',
            '/images/men-white-black-shoes-4.jpg',
        ]
    },
    {
        id: 5,
        title: 'U.S. Polo Assn.',
        subtitle: 'Men Walking Shoes',
        description: 'Men Mesh Walking Shoes',
        category: 'Shoes',
        rating: 4.8,
        ratingCount: '3.9k',
        price: '2579',
        stock: 23,
        image: [
            '/images/men-white-shoes-1.jpg',
            '/images/men-white-shoes-2.jpg',
            '/images/men-white-shoes-3.jpg',
            '/images/men-white-shoes-4.jpg',
        ]
    },
    {
        id: 6,
        title: 'Puma',
        subtitle: 'Unisex FF LBK  Running Shoes',
        description: 'Unisex FlexFocus Lite Better Knit Running Shoes',
        category: 'Shoes',
        rating: 3.2,
        ratingCount: '2.7k',
        price: '4676',
        stock: 112,
        image: [
            '/images/men-gray-shoes-1.jpg',
            '/images/men-gray-shoes-2.jpg',
            '/images/men-gray-shoes-3.jpg',
            '/images/men-gray-shoes-4.jpg',
        ]
    },
    {
        id: 7,
        title: 'Titan',
        subtitle: 'Watches',
        description: 'Men Black Dial Watch 1639SM02',
        category: 'Watch',
        rating: 4.5,
        ratingCount: '2.7k',
        price: '1995',
        stock: 308,
        image: [
            '/images/men-watch-titan-1.jpg',
            '/images/men-watch-titan-2.jpg',
            '/images/men-watch-titan-3.jpg',
            '/images/men-watch-titan-4.jpg',
        ]
    },
    {
        id: 8,
        title: 'Fossil',
        subtitle: 'Men Analogue Watch',
        description: 'Men Cream-Coloured Analogue Watch FS5439I',
        category: 'Watch',
        rating: 4.3,
        ratingCount: '199',
        price: '4997',
        stock: 155,
        image: [
            '/images/men-watch-fossil-1.jpg',
            '/images/men-watch-fossil-2.jpg',
            '/images/men-watch-fossil-3.jpg',
            '/images/men-watch-fossil-4.jpg',
        ]
    },
    {
        id: 9,
        title: 'Fastrack',
        subtitle: 'Men Analogue Watch',
        description: 'Men Black Analogue Watch 38058PP01',
        category: 'Watch',
        rating: 4.3,
        ratingCount: '934',
        price: '1595',
        stock: 103,
        image: [
            '/images/men-watch-fastrack-1.jpg',
            '/images/men-watch-fastrack-2.jpg',
            '/images/men-watch-fastrack-3.jpg',
            '/images/men-watch-fastrack-4.jpg',
        ]
    },
    {
        id: 10,
        title: 'Levis',
        subtitle: 'Men Slim Fit Jeans',
        description: 'Men 511 Slim Fit Light Fade Stretchable Jeans',
        category: 'Jeans',
        rating: 4.1,
        ratingCount: '3.2k',
        price: '1375',
        stock: 542,
        image: [
            '/images/stretchable-jeans-1.jpg',
            '/images/stretchable-jeans-2.jpg',
            '/images/stretchable-jeans-3.jpg',
            '/images/stretchable-jeans-4.jpg',
        ]
    },
    {
        id: 11,
        title: 'Levis',
        subtitle: 'Men 511 Slim Fit Jeans',
        description: 'Men 511 Slim Fit Heavy Fade Stretchable Jeans',
        category: 'Jeans',
        rating: 4.2,
        ratingCount: '898',
        price: '1889',
        stock: 42,
        image: [
            '/images/slim-jeans-1.jpg',
            '/images/slim-jeans-2.jpg',
            '/images/slim-jeans-3.jpg',
            '/images/slim-jeans-4.jpg',
        ]
    },
    {
        id: 12,
        title: 'Levis',
        subtitle: 'Men Slim Fit Jeans',
        description: 'Men Slim Fit Light Fade Stretchable Jeans',
        category: 'Jeans',
        rating: 4.2,
        ratingCount: '1.4k',
        price: '1246',
        stock: 402,
        image: [
            '/images/trapped-jeans-1.jpg',
            '/images/trapped-jeans-2.jpg',
            '/images/trapped-jeans-3.jpg',
            '/images/trapped-jeans-4.jpg',
        ]
    },
]